name: Qodana
on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        env:
          QODANA_TOKEN: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzWDZ4OSIsInByb2plY3QiOiJBNktQeSIsInRva2VuIjoiQURiRWQifQ.DA89mCusy5c01LK3ELayjhJNGhdJeyGXfzEjdccMEfM'
        uses: JetBrains/qodana-action@v2022.3.0